### ISSUE TITLE
eval corpus 'cyrus' points to wrong file

### ISSUE THREAD

**Issue by lgessler** [CopticScriptorium/coptic-nlp#25]
When I run the following I get an error:

```bash
$ cd lib
$ python binder.py xgboost
Traceback (most recent call last):
  File "binder.py", line 568, in <module>
    main()
  File "binder.py", line 563, in main
    opts
  File "binder.py", line 371, in run_eval
    test_gold = prepare_gold_text(test_gold_list)
  File "binder.py", line 116, in prepare_gold_text
    text = read_and_combine_files(gold_list)
  File "binder.py", line 73, in read_and_combine_files
    contents += io.open(f, encoding="utf8").read().strip() + "\n"
FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/coptic-nlp/eval/utils/../unreleased/BritMusOriental6783_27a_30a.tt'
```

By default, binder.py uses `cyrus` for its `test_list`, and [`cyrus` includes `BritMusOriental6783_27a_30a.tt`](https://github.com/CopticScriptorium/coptic-nlp/blob/dev/eval/utils/eval_utils.py#L157L160).

I think this file must have been renamed to something else, but it's not immediately clear to me what. Or maybe it hasn't been committed?

**Comment by lgessler** [comment]
I'm also having trouble with a few other corpora like victor2 and proclus. I think their files must also have not been committed?

**Comment by amir-zeldes** [comment]
Sorry about that, they should be in 1646f6a817e40a2b9f177d588be30013cc3d0072 . Note that Victor 2 is not yet corrected, so you shouldn't train on it (or test yet really either)
