### ISSUE TITLE
Add multiword expression spans

### ISSUE THREAD

**Issue by amir-zeldes** [CopticScriptorium/coptic-nlp#5]
1. Use CDO database to identify valid MWEs that have dictionary entries
2. Create spans for MWEs by scanning window of n norms/lemmas and looking up in entry list
3. Prevent overlapping spans (use heuristic, e.g. first span wins)

Spans annotations should then received lemma link-like visualization in ANNIS grid, and ideally some analogous overlapping solution in document view (could be done with superscripts or double underlines à la coref vis)

**Comment by ctschroeder** [comment]
Is this something we are going to do to existing corpora or only new corpora?

**Comment by amir-zeldes** [comment]
I added them to the release candidates of the existing corpora as well; I expect we'll be adding them to anything that gets (re)released, but for now since it's 100% automatic, I'm adding it during conversion, not in GitDox. If we ever decide we want to manually correct them, then they will have to be materialized in GitDox as well.
